# Copyright 2017 ChaiShushan <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

env:
  - CXX=g++-4.8
addons:
apt:
sources:
  - ubuntu-toolchain-r-test
packages:
  - g++-4.8

language: node_js

node_js:
  - "7"

script:
# Output useful info for debugging
  - node --version
  - npm --version
# Run tests
  - npm test

